elementary/switchboard-plug-power

cli/Systemd.vala
cli/main.vala
src/ActionComboBox.vala
src/Battery.vala
src/CliCommunicator.vala
src/Interfaces.vala
src/LidCloseActionComboBox.vala
src/Permission.vala
src/Plug.vala
src/PowerSupply.vala
src/TimeoutComboBox.vala
src/Translations.vala

Fix FSF address in license preambles

---

src/LidCloseActionComboBox.vala
src/Plug.vala

This fixes terrible depending on label's showing in the UI (as if this ever worked). I'm not sure if the provided boolean values are correct so someone with a laptop must test.

Fix lid states

---

cli/CMakeLists.txt
src/CMakeLists.txt

build: Avoid ".."-referenes and use CMAKE_SOURCE_DIR instead

---

src/Interfaces.vala

This isn't a build option anymore

remove last reference to OLD_GSD

---

src/Plug.vala

**Make switchboard plug-power smart**

Smart hardware detection

---

src/Plug.vala

Fixes #49 
Fixes #51 
- method to detect battery
- if system has battery display proper settings
- laptop-detect script & laptop_detect removed
- handle GLib2.errors
- better indentation

Battery detection

---

src/Battery.vala
src/Plug.vala

This functionality is already provided by the Battery class
Needs confirmation from someone on desktop

Use battery presence from Battery.vala

---

src/Battery.vala

- get rid of laptop term
- remove unnecessary condition

Simplified Battery.check_present & more clear terminology

---

src/Battery.vala
src/Plug.vala

- do not debug when there's no battery
- use more clear and consistent terms
- better and consistent debug messages

Make battery method more clear and consistent

---

src/Plug.vala

Fixes broken brightness slider in Juno

Update DBus name

---

.travis.yml
README.md
cli/meson.build
meson.build

fixes  #74
There has been a missing commit in this switch for sure :disappointed:

meson: add missing file and set the right directory

---

src/Plug.vala

Turns out it's the same number of lines and this way we're not doing any mad lad confusing conditionals

Plug.vala: Don't be too clever about building ac/battery settings

---

src/Plug.vala

* Get rid of some single-use methods
* Reduce variable scope when possible
* Replace lid widget sensitivity logic with property bindings

Remove single-use methods

---

src/Widgets/ActionComboBox.vala

Fixes #78 unless/until hibernation is fixed/enabled in the OS.

Remove broken hibernate option

---

src/Widgets/ActionComboBox.vala

Added interactive "Prompt to shutdown" option in power button menu

---

src/GreeterAccountsServicePlugin.vala
src/Widgets/TimeoutComboBox.vala
src/meson.build

Fixes #89 when used in conjunction with https://github.com/elementary/greeter/pull/343
Requires https://github.com/elementary/default-settings/pull/134 to work but won't crash without it.

Set AccountsService power keys

---

data/power.appdata.xml.in

For better display in Feedback and AppCenter

AppData: Add "Settings" to name

---

src/Plug.vala

Plug: Add search terms for sleep timeout

---

src/Battery.vala
src/MainView.vala

Show percentage switch

---

src/MainView.vala

No functional or visual change, just updating to modern code style.

MainView: Modern code style

---

src/MainView.vala

Follow-up for #193. It's not immediately clear what the "show percentage" affects, so I clarified while using similar language to other indicator toggles.

MainView: clarify battery percent label

---

src/MainView.vala
src/Widgets/LidCloseActionComboBox.vala

Authenticate on demand for lid close settings

---

src/MainView.vala

Fixes https://github.com/elementary/switchboard-plug-power/issues/210

Expose automatic lower power mode setting

---

src/MainView.vala

MainView: subclass SettingsPage

---

src/MainView.vala
src/Widgets/PowerModeButton.vala

Complementary to https://github.com/elementary/settings-daemon/pull/123

Use settings-daemon to manage power profiles
